import {
  Document,
  Page,
  View,
  Text,
  Image,
  StyleSheet,
} from "@react-pdf/renderer";

const BRAND = "Bolo Bill";
const FOOTER_TEXT = `Generated by ${BRAND}`;

function formatPrice(amount: number): string {
  return `Rs ${Number(amount).toFixed(2)}`;
}

const styles = StyleSheet.create({
  page: {
    padding: 0,
    fontFamily: "Helvetica",
    fontSize: 10,
  },
  watermark: {
    position: "absolute",
    left: 0,
    top: "50%",
    width: "100%",
    textAlign: "center",
    transform: "translateY(-50%) rotate(-28deg)",
    fontSize: 72,
    color: "#cccccc",
    fontFamily: "Helvetica-Bold",
  },
  header: {
    backgroundColor: "#e66239",
    paddingHorizontal: 32,
    paddingTop: 14,
    paddingBottom: 12,
    marginBottom: 24,
  },
  headerBrand: {
    color: "#ffffff",
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
  },
  headerLabel: {
    color: "#ffffff",
    fontSize: 11,
    marginTop: 4,
  },
  section: {
    paddingHorizontal: 32,
    marginBottom: 8,
  },
  row: {
    flexDirection: "row",
    marginBottom: 14,
  },
  label: {
    fontSize: 9,
    color: "#6b7280",
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  value: {
    fontSize: 10,
    color: "#111827",
  },
  colLeft: {
    width: "45%",
  },
  colRight: {
    width: "55%",
    paddingLeft: 40,
  },
  itemsTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#111827",
    marginBottom: 14,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 0.6,
    borderBottomColor: "#d1d5db",
    paddingBottom: 6,
    marginBottom: 10,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#4b5563",
  },
  thItem: { width: "50%" },
  thQty: { width: "12%", textAlign: "right" },
  thPrice: { width: "18%", textAlign: "right" },
  thTotal: { width: "20%", textAlign: "right" },
  tableRow: {
    flexDirection: "row",
    fontSize: 9,
    marginBottom: 6,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFF7ED",
    borderWidth: 0.5,
    borderColor: "#e66239",
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginTop: 10,
    marginBottom: 14,
  },
  totalLabel: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: "#111827",
  },
  totalValue: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: "#111827",
  },
  qrBox: {
    alignSelf: "flex-end",
    backgroundColor: "#FFF7ED",
    borderWidth: 0.5,
    borderColor: "#e66239",
    padding: 8,
    alignItems: "center",
    width: 112,
    marginTop: 8,
  },
  qrLabel: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#9a3412",
    marginBottom: 6,
  },
  qrImage: {
    width: 88,
    height: 88,
  },
  footer: {
    position: "absolute",
    bottom: 22,
    left: 32,
    right: 32,
    textAlign: "center",
    fontSize: 8,
    color: "#9ca3af",
  },
});

export type InvoicePdfItem = {
  name: string;
  quantity: string;
  totalPrice: number;
};

export type InvoicePdfDocumentProps = {
  invoiceId: string;
  customerName: string;
  createdBy?: string;
  items: InvoicePdfItem[];
  total: number;
  createdAt: string;
  source?: string;
  /** QR image: URL or data URL (same image as uploaded in admin) */
  qrImageSrc?: string;
};

export function InvoicePdfDocument({
  invoiceId,
  customerName,
  createdBy,
  items,
  total,
  createdAt,
  source,
  qrImageSrc,
}: InvoicePdfDocumentProps) {
  const dateStr = createdAt
    ? new Date(createdAt).toLocaleString()
    : "—";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.watermark}>{BRAND}</Text>

        <View style={styles.header}>
          <Text style={styles.headerBrand}>{BRAND}</Text>
          <Text style={styles.headerLabel}>INVOICE</Text>
        </View>

        <View style={styles.section}>
          <View style={styles.row}>
            <View style={styles.colLeft}>
              <Text style={styles.label}>Invoice ID</Text>
              <Text style={styles.value}>{invoiceId}</Text>
            </View>
            <View style={styles.colRight}>
              <Text style={styles.label}>Date</Text>
              <Text style={styles.value}>{dateStr}</Text>
            </View>
          </View>
          <View style={styles.row}>
            <View style={styles.colLeft}>
              <Text style={styles.label}>Created by</Text>
              <Text style={styles.value}>{createdBy ?? "—"}</Text>
            </View>
            <View style={styles.colRight}>
              <Text style={styles.label}>Customer</Text>
              <Text style={styles.value}>{customerName}</Text>
            </View>
          </View>
          {source ? (
            <View style={[styles.row, { marginBottom: 14 }]}>
              <View style={styles.colLeft}>
                <Text style={styles.label}>Source</Text>
                <Text style={styles.value}>{source}</Text>
              </View>
            </View>
          ) : null}
        </View>

        <View style={styles.section}>
          <Text style={styles.itemsTitle}>Items</Text>
          <View style={styles.tableHeader}>
            <Text style={styles.thItem}>Item</Text>
            <Text style={styles.thQty}>Qty</Text>
            <Text style={styles.thPrice}>Price</Text>
            <Text style={styles.thTotal}>Total</Text>
          </View>
          {items.map((item, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={styles.thItem}>{item.name.substring(0, 48)}</Text>
              <Text style={styles.thQty}>{String(item.quantity)}</Text>
              <Text style={styles.thPrice}>{formatPrice(item.totalPrice)}</Text>
              <Text style={styles.thTotal}>{formatPrice(item.totalPrice)}</Text>
            </View>
          ))}
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Total</Text>
            <Text style={styles.totalValue}>{formatPrice(total)}</Text>
          </View>
          {qrImageSrc ? (
            <View style={styles.qrBox}>
              <Text style={styles.qrLabel}>Scan to pay</Text>
              <Image style={styles.qrImage} src={qrImageSrc} />
            </View>
          ) : null}
        </View>

        <Text style={styles.footer}>{FOOTER_TEXT}</Text>
      </Page>
    </Document>
  );
}
