import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import {InvoiceItemInput} from './transcriptParser.service';
import {env} from '../config/env';

type GeneratePdfInput = {
  invoiceId: string;
  customerName: string;
  customerPhone: string;
  items: InvoiceItemInput[];
  total: number;
  transcript?: string;
  billToName?: string;
  billToPhone?: string;
};

const pdfDir = path.join(process.cwd(), 'storage/pdfs');
if (!fs.existsSync(pdfDir)) {
  fs.mkdirSync(pdfDir, {recursive: true});
}

const BRAND = 'Bolo Bill';
const FOOTER_TEXT = `Generated by ${BRAND}`;

/** Same design as admin export PDF, with BoloBill watermark behind. */
export const generateInvoicePdf = async (
  input: GeneratePdfInput,
): Promise<{pdfPath: string; pdfUrl: string}> => {
  const fileName = `invoice-${input.invoiceId}.pdf`;
  const absPath = path.join(pdfDir, fileName);
  const createdAt = new Date().toLocaleString('en-IN');
  const createdBy = input.customerName?.trim()
    ? [input.customerName, input.customerPhone].filter(Boolean).join(' — ') || input.customerPhone || '—'
    : input.customerPhone || '—';
  const customerName = input.billToName?.trim() || 'Customer';
  const source = input.transcript?.trim() ? 'voice' : 'manual';

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({size: 'A4', margin: 0});
    const stream = fs.createWriteStream(absPath);
    doc.pipe(stream);

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const margin = 18;
    const leftCol = margin;
    const rightCol = margin + 95;
    const tableItemX = margin;
    const tableQtyX = 95;
    const tablePriceX = 130;
    const tableTotalX = 165;
    const tableRight = pageWidth - margin;
    const rowHeight = 6;
    const pageBreakY = pageHeight - 50;

    const formatPrice = (amount: number) => `Rs ${Number(amount).toFixed(2)}`;

    const drawWatermark = () => {
      doc.save();
      doc.fillColor('#cccccc');
      doc.opacity(0.12);
      doc.rotate(-28, {origin: [pageWidth / 2, pageHeight / 2]});
      doc.fontSize(72).font('Helvetica-Bold').text('BoloBill', 0, pageHeight / 2 - 36, {
        width: pageWidth,
        align: 'center',
      });
      doc.restore();
    };

    const drawHeader = (y: number) => {
      doc.rect(0, y, pageWidth, 28).fill('#e66239');
      doc.fillColor('#ffffff').fontSize(18).font('Helvetica-Bold').text(BRAND, leftCol, y + 10);
      doc.fontSize(11).font('Helvetica').text('Invoice', leftCol, y + 20);
      doc.fillColor('#000000');
    };

    let y = margin;

    drawWatermark();
    drawHeader(0);
    y = 36;

    doc.fontSize(9).fillColor('#646464').font('Helvetica-Bold');
    doc.text('Invoice ID', leftCol, y);
    doc.text('Date', rightCol, y);
    doc.fontSize(10).fillColor('#000000').font('Helvetica');
    doc.text(input.invoiceId, leftCol, y + 5);
    doc.text(createdAt, rightCol, y + 5);
    y += 14;

    doc.fontSize(9).fillColor('#646464').font('Helvetica-Bold');
    doc.text('Created by', leftCol, y);
    doc.text('Customer', rightCol, y);
    doc.fontSize(10).fillColor('#000000').font('Helvetica');
    doc.text(createdBy, leftCol, y + 5);
    doc.text(customerName, rightCol, y + 5);
    y += 14;

    doc.fontSize(9).fillColor('#646464').font('Helvetica-Bold');
    doc.text('Source', leftCol, y);
    doc.fontSize(10).fillColor('#000000').font('Helvetica');
    doc.text(source, leftCol, y + 5);
    y += 18;

    doc.fontSize(10).font('Helvetica-Bold').text('Items', leftCol, y);
    y += 8;

    doc.strokeColor('#c8c8c8').lineWidth(0.5);
    doc.moveTo(margin, y).lineTo(tableRight, y).stroke();
    y += 6;

    doc.fontSize(9).font('Helvetica-Bold').fillColor('#505050');
    doc.text('Item', tableItemX, y);
    doc.text('Qty', tableQtyX, y);
    doc.text('Price', tablePriceX, y);
    doc.text('Total', tableTotalX, y);
    doc.fillColor('#000000').font('Helvetica');
    y += 6;

    doc.moveTo(margin, y).lineTo(tableRight, y).stroke();
    y += 5;

    for (const item of input.items) {
      if (y > pageBreakY) {
        doc.addPage();
        drawWatermark();
        y = margin;
        doc.fontSize(9);
      }
      const name = (item.name || '').substring(0, 38);
      const qty = String(item.quantity ?? '');
      const price = formatPrice(Number(item.totalPrice));
      doc.text(name, tableItemX, y);
      doc.text(qty, tableQtyX, y);
      doc.text(price, tablePriceX, y);
      doc.text(price, tableTotalX, y);
      y += rowHeight;
    }

    y += 4;
    doc.moveTo(margin, y).lineTo(tableRight, y).stroke();
    y += 10;
    doc.fontSize(11).font('Helvetica-Bold');
    doc.text('Total', margin, y);
    doc.text(formatPrice(input.total), tableTotalX, y);
    doc.font('Helvetica');

    if (input.transcript?.trim()) {
      y += 16;
      doc.fontSize(9).fillColor('#646464').font('Helvetica-Bold').text('Transcript', leftCol, y);
      doc.fontSize(9).fillColor('#000000').font('Helvetica');
      doc.text(input.transcript.trim().substring(0, 400), leftCol, y + 5, {width: pageWidth - margin * 2});
    }

    const footerY = pageHeight - 12;
    doc.fontSize(8).fillColor('#8c8c8c');
    doc.text(FOOTER_TEXT, pageWidth / 2, footerY, {align: 'center', width: pageWidth});
    doc.fillColor('#000000');

    doc.end();

    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  return {
    pdfPath: absPath,
    pdfUrl: `${env.BASE_URL}/api/files/pdfs/${fileName}`,
  };
};
