import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import {InvoiceItemInput} from './transcriptParser.service';
import {env} from '../config/env';

type GeneratePdfInput = {
  invoiceId: string;
  customerName: string;
  customerPhone: string;
  items: InvoiceItemInput[];
  total: number;
  transcript?: string;
  billToName?: string;
  billToPhone?: string;
  /** Path to QR code image (e.g. UPI) to embed in PDF for "Scan to pay". */
  qrImagePath?: string;
};

const pdfDir = path.join(process.cwd(), 'storage/pdfs');
if (!fs.existsSync(pdfDir)) {
  fs.mkdirSync(pdfDir, {recursive: true});
}

const BRAND = 'Bolo Bill';
const FOOTER_TEXT = `Generated by ${BRAND}`;

/** Attractive invoice PDF: clear spacing, no overlapping. Total computed from items so it always matches the table. */
export const generateInvoicePdf = async (
  input: GeneratePdfInput,
): Promise<{pdfPath: string; pdfUrl: string}> => {
  const fileName = `invoice-${input.invoiceId}.pdf`;
  const absPath = path.join(pdfDir, fileName);
  const createdAt = new Date().toLocaleString('en-IN');
  const createdBy = input.customerName?.trim()
    ? [input.customerName, input.customerPhone].filter(Boolean).join(' — ') || input.customerPhone || '—'
    : input.customerPhone || '—';
  const customerName = input.billToName?.trim() || 'Customer';
  const source = input.transcript?.trim() ? 'voice' : 'manual';
  const computedTotal = input.items.reduce((sum, item) => sum + Number(item.totalPrice || 0), 0);

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({size: 'A4', margin: 0});
    const stream = fs.createWriteStream(absPath);
    doc.pipe(stream);

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const margin = 32;
    const tableRight = pageWidth - margin;
    const contentWidth = pageWidth - margin * 2;
    const leftColWidth = 220;
    const rightColStart = margin + leftColWidth + 40;
    const rightColWidth = tableRight - rightColStart;
    const rowBlockHeight = 22;
    const pageBreakY = pageHeight - 70;

    const formatPrice = (amount: number) => `Rs ${Number(amount).toFixed(2)}`;

    const drawWatermark = () => {
      doc.save();
      doc.fillColor('#e0e0e0');
      doc.opacity(0.08);
      doc.rotate(-28, {origin: [pageWidth / 2, pageHeight / 2]});
      doc.fontSize(80).font('Helvetica-Bold').text('Bolo Bill', 0, pageHeight / 2 - 40, {
        width: pageWidth,
        align: 'center',
      });
      doc.restore();
    };

    const headerHeight = 52;
    const drawHeader = (y: number) => {
      doc.rect(0, y, pageWidth, headerHeight).fill('#e66239');
      doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold').text(BRAND, margin, y + 14, { width: contentWidth });
      doc.fontSize(11).font('Helvetica').text('INVOICE', margin, y + 34, { width: contentWidth });
      doc.strokeColor('#d97706').lineWidth(0.5).moveTo(0, y + headerHeight).lineTo(pageWidth, y + headerHeight).stroke();
      doc.fillColor('#000000');
    };

    let y = margin;

    drawWatermark();
    drawHeader(0);
    y = headerHeight + 24;

    doc.fontSize(9).fillColor('#6b7280').font('Helvetica-Bold');
    doc.text('Invoice ID', margin, y);
    doc.text('Date', rightColStart, y);
    y += 12;
    doc.fontSize(10).fillColor('#111827').font('Helvetica');
    doc.text(input.invoiceId, margin, y, {width: leftColWidth});
    doc.text(createdAt, rightColStart, y, {width: rightColWidth});
    y += rowBlockHeight;

    doc.fontSize(9).fillColor('#6b7280').font('Helvetica-Bold');
    doc.text('Created by', margin, y);
    doc.text('Customer', rightColStart, y);
    y += 12;
    doc.fontSize(10).fillColor('#111827').font('Helvetica');
    doc.text(createdBy, margin, y, {width: leftColWidth});
    doc.text(customerName, rightColStart, y, {width: rightColWidth});
    y += rowBlockHeight;

    doc.fontSize(9).fillColor('#6b7280').font('Helvetica-Bold');
    doc.text('Source', margin, y);
    y += 12;
    doc.fontSize(10).fillColor('#111827').font('Helvetica');
    doc.text(source, margin, y, {width: leftColWidth});
    y += rowBlockHeight + 8;

    doc.fontSize(11).font('Helvetica-Bold').fillColor('#111827').text('Items', margin, y);
    y += 14;

    const tableTopY = y;
    doc.strokeColor('#d1d5db').lineWidth(0.6);
    doc.moveTo(margin, y).lineTo(tableRight, y).stroke();
    y += 12;

    const tableItemX = margin;
    const tableItemWidth = 230;
    const tableQtyX = margin + tableItemWidth + 16;
    const tableQtyWidth = 44;
    const tablePriceX = tableQtyX + tableQtyWidth + 16;
    const tablePriceWidth = 78;
    const tableTotalX = tablePriceX + tablePriceWidth + 16;
    const tableTotalWidth = tableRight - tableTotalX;
    const rowHeight = 14;

    doc.rect(margin, y - 2, tableRight - margin, 16).fill('#f3f4f6');
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#4b5563');
    doc.text('Item', tableItemX, y, {width: tableItemWidth});
    doc.text('Qty', tableQtyX, y, {width: tableQtyWidth});
    doc.text('Price', tablePriceX, y, {width: tablePriceWidth, align: 'right'});
    doc.text('Total', tableTotalX, y, {width: tableTotalWidth, align: 'right'});
    doc.fillColor('#111827').font('Helvetica');
    y += 14;

    doc.moveTo(margin, y).lineTo(tableRight, y).stroke();
    y += 10;

    for (const item of input.items) {
      if (y > pageBreakY) {
        doc.addPage();
        drawWatermark();
        y = margin;
        doc.fontSize(9);
      }
      const name = (item.name || '').substring(0, 48);
      const qty = String(item.quantity ?? '');
      const priceStr = formatPrice(Number(item.totalPrice));
      doc.fontSize(9).text(name, tableItemX, y, {width: tableItemWidth});
      doc.text(qty, tableQtyX, y, {width: tableQtyWidth});
      doc.text(priceStr, tablePriceX, y, {width: tablePriceWidth, align: 'right'});
      doc.text(priceStr, tableTotalX, y, {width: tableTotalWidth, align: 'right'});
      y += rowHeight;
    }

    y += 10;
    doc.moveTo(margin, y).lineTo(tableRight, y).stroke();
    y += 2;
    doc.rect(margin, y, tableRight - margin, 22).fillAndStroke('#FFF7ED', '#e66239');
    y += 6;
    doc.fontSize(13).font('Helvetica-Bold').fillColor('#111827');
    const totalLabelY = y;
    doc.text('Total', margin + 8, totalLabelY);
    doc.text(formatPrice(computedTotal), tableTotalX, totalLabelY, { width: tableTotalWidth - 8, align: 'right' });
    doc.font('Helvetica').fontSize(10);
    y += 22;

    const qrSize = 88;
    const qrBoxX = tableRight - qrSize - 8;
    const hasQr = input.qrImagePath && fs.existsSync(input.qrImagePath);
    if (hasQr) {
      const qrBoxY = y;
      doc.roundedRect(qrBoxX - 4, qrBoxY - 2, qrSize + 24, qrSize + 28, 4).fillAndStroke('#FFF7ED', '#e66239');
      doc.fontSize(9).fillColor('#9a3412').font('Helvetica-Bold').text('Scan to pay', qrBoxX - 4, qrBoxY + 4, { width: qrSize + 24, align: 'center' });
      doc.image(input.qrImagePath!, qrBoxX, qrBoxY + 16, { width: qrSize, height: qrSize });
      y += qrSize + 32;
    }

    if (input.transcript?.trim()) {
      doc.fontSize(9).fillColor('#6b7280').font('Helvetica-Bold').text('Transcript', margin, y);
      y += 12;
      doc.fontSize(9).fillColor('#374151').font('Helvetica');
      doc.text(input.transcript.trim().substring(0, 500), margin, y, {width: contentWidth});
      y += 28;
    }

    const footerY = pageHeight - 22;
    doc.strokeColor('#e5e7eb').lineWidth(0.5).moveTo(margin, footerY - 10).lineTo(tableRight, footerY - 10).stroke();
    doc.fontSize(8).fillColor('#9ca3af');
    doc.text(FOOTER_TEXT, margin, footerY, {align: 'center', width: contentWidth});
    doc.fillColor('#000000');

    doc.end();

    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  return {
    pdfPath: absPath,
    pdfUrl: `${env.BASE_URL}/api/files/pdfs/${fileName}`,
  };
};
