import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import {InvoiceItemInput} from './transcriptParser.service';
import {env} from '../config/env';

type GeneratePdfInput = {
  invoiceId: string;
  customerName: string;
  customerPhone: string;
  items: InvoiceItemInput[];
  total: number;
  transcript?: string;
  billToName?: string;
  billToPhone?: string;
};

const pdfDir = path.join(process.cwd(), 'storage/pdfs');
if (!fs.existsSync(pdfDir)) {
  fs.mkdirSync(pdfDir, {recursive: true});
}

const BRAND = 'Bolo Bill';
const FOOTER_TEXT = `Generated by ${BRAND}`;

/** Same design as admin export PDF, with BoloBill watermark behind. Clear layout, no overlapping. */
export const generateInvoicePdf = async (
  input: GeneratePdfInput,
): Promise<{pdfPath: string; pdfUrl: string}> => {
  const fileName = `invoice-${input.invoiceId}.pdf`;
  const absPath = path.join(pdfDir, fileName);
  const createdAt = new Date().toLocaleString('en-IN');
  const createdBy = input.customerName?.trim()
    ? [input.customerName, input.customerPhone].filter(Boolean).join(' — ') || input.customerPhone || '—'
    : input.customerPhone || '—';
  const customerName = input.billToName?.trim() || 'Customer';
  const source = input.transcript?.trim() ? 'voice' : 'manual';

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({size: 'A4', margin: 0});
    const stream = fs.createWriteStream(absPath);
    doc.pipe(stream);

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const margin = 24;
    const tableRight = pageWidth - margin;
    const contentWidth = pageWidth - margin * 2;
    const leftColWidth = 260;
    const rightColStart = margin + leftColWidth + 24;
    const rightColWidth = tableRight - rightColStart;
    const pageBreakY = pageHeight - 55;

    const formatPrice = (amount: number) => `Rs ${Number(amount).toFixed(2)}`;

    const drawWatermark = () => {
      doc.save();
      doc.fillColor('#cccccc');
      doc.opacity(0.12);
      doc.rotate(-28, {origin: [pageWidth / 2, pageHeight / 2]});
      doc.fontSize(72).font('Helvetica-Bold').text('BoloBill', 0, pageHeight / 2 - 36, {
        width: pageWidth,
        align: 'center',
      });
      doc.restore();
    };

    const headerHeight = 36;
    const drawHeader = (y: number) => {
      doc.rect(0, y, pageWidth, headerHeight).fill('#e66239');
      doc.fillColor('#ffffff').fontSize(18).font('Helvetica-Bold').text(BRAND, margin, y + 10, {width: contentWidth});
      doc.fontSize(11).font('Helvetica').text('Invoice', margin, y + 24, {width: contentWidth});
      doc.fillColor('#000000');
    };

    let y = margin;

    drawWatermark();
    drawHeader(0);
    y = headerHeight + 14;

    doc.fontSize(9).fillColor('#646464').font('Helvetica-Bold');
    doc.text('Invoice ID', margin, y);
    doc.text('Date', rightColStart, y);
    doc.fontSize(10).fillColor('#000000').font('Helvetica');
    doc.text(input.invoiceId, margin, y + 6, {width: leftColWidth});
    doc.text(createdAt, rightColStart, y + 6, {width: rightColWidth});
    y += 20;

    doc.fontSize(9).fillColor('#646464').font('Helvetica-Bold');
    doc.text('Created by', margin, y);
    doc.text('Customer', rightColStart, y);
    doc.fontSize(10).fillColor('#000000').font('Helvetica');
    doc.text(createdBy, margin, y + 6, {width: leftColWidth});
    doc.text(customerName, rightColStart, y + 6, {width: rightColWidth});
    y += 20;

    doc.fontSize(9).fillColor('#646464').font('Helvetica-Bold');
    doc.text('Source', margin, y);
    doc.fontSize(10).fillColor('#000000').font('Helvetica');
    doc.text(source, margin, y + 6, {width: leftColWidth});
    y += 24;

    doc.fontSize(10).font('Helvetica-Bold').text('Items', margin, y);
    y += 10;

    doc.strokeColor('#c8c8c8').lineWidth(0.5);
    doc.moveTo(margin, y).lineTo(tableRight, y).stroke();
    y += 8;

    const tableItemX = margin;
    const tableItemWidth = 270;
    const tableQtyX = margin + tableItemWidth + 8;
    const tableQtyWidth = 52;
    const tablePriceX = tableQtyX + tableQtyWidth + 8;
    const tablePriceWidth = 88;
    const tableTotalX = tablePriceX + tablePriceWidth + 8;
    const tableTotalWidth = tableRight - tableTotalX;
    const rowHeight = 10;

    doc.fontSize(9).font('Helvetica-Bold').fillColor('#505050');
    doc.text('Item', tableItemX, y, {width: tableItemWidth});
    doc.text('Qty', tableQtyX, y, {width: tableQtyWidth});
    doc.text('Price', tablePriceX, y, {width: tablePriceWidth, align: 'right'});
    doc.text('Total', tableTotalX, y, {width: tableTotalWidth, align: 'right'});
    doc.fillColor('#000000').font('Helvetica');
    y += 8;

    doc.moveTo(margin, y).lineTo(tableRight, y).stroke();
    y += 6;

    for (const item of input.items) {
      if (y > pageBreakY) {
        doc.addPage();
        drawWatermark();
        y = margin;
        doc.fontSize(9);
      }
      const name = (item.name || '').substring(0, 48);
      const qty = String(item.quantity ?? '');
      const priceStr = formatPrice(Number(item.totalPrice));
      doc.fontSize(9).text(name, tableItemX, y, {width: tableItemWidth});
      doc.text(qty, tableQtyX, y, {width: tableQtyWidth});
      doc.text(priceStr, tablePriceX, y, {width: tablePriceWidth, align: 'right'});
      doc.text(priceStr, tableTotalX, y, {width: tableTotalWidth, align: 'right'});
      y += rowHeight;
    }

    y += 6;
    doc.moveTo(margin, y).lineTo(tableRight, y).stroke();
    y += 12;
    doc.fontSize(11).font('Helvetica-Bold');
    doc.text('Total', margin, y);
    doc.text(formatPrice(input.total), tableTotalX, y, {width: tableTotalWidth, align: 'right'});
    doc.font('Helvetica');

    if (input.transcript?.trim()) {
      y += 20;
      doc.fontSize(9).fillColor('#646464').font('Helvetica-Bold').text('Transcript', margin, y);
      doc.fontSize(9).fillColor('#000000').font('Helvetica');
      doc.text(input.transcript.trim().substring(0, 500), margin, y + 6, {width: contentWidth});
    }

    const footerY = pageHeight - 14;
    doc.fontSize(8).fillColor('#8c8c8c');
    doc.text(FOOTER_TEXT, margin, footerY, {align: 'center', width: contentWidth});
    doc.fillColor('#000000');

    doc.end();

    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  return {
    pdfPath: absPath,
    pdfUrl: `${env.BASE_URL}/api/files/pdfs/${fileName}`,
  };
};
