import { jsPDF } from 'jspdf';

type InvoiceItem = { name: string; quantity: string; totalPrice: number };

const BRAND = 'Bolo Bill';
const FOOTER_TEXT = `Generated by ${BRAND}`;

/** Format price for PDF (use "Rs" to avoid font/symbol issues that show as "1") */
function formatPrice(amount: number): string {
  return `Rs ${amount}`;
}

export function exportInvoiceAsPdf(params: {
  invoiceId: string;
  customerName: string;
  createdBy?: string;
  items: InvoiceItem[];
  total: number;
  createdAt: string;
  source?: string;
}) {
  const doc = new jsPDF();
  const margin = 18;
  const pageW = doc.internal.pageSize.getWidth();
  let y = margin;

  // ----- Header: Bolo Bill branding -----
  doc.setFillColor(230, 98, 57); // primary orange
  doc.rect(0, 0, pageW, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(BRAND, margin, 18);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Invoice', margin, 25);
  doc.setTextColor(0, 0, 0);
  y = 36;

  // ----- Invoice details block -----
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const leftCol = margin;
  const rightCol = margin + 95;

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  doc.text('Invoice ID', leftCol, y);
  doc.text('Date', rightCol, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(params.invoiceId, leftCol, y + 5);
  doc.text(
    params.createdAt ? new Date(params.createdAt).toLocaleString() : '—',
    rightCol,
    y + 5
  );
  y += 14;

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  doc.text('Created by', leftCol, y);
  doc.text('Customer', rightCol, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(params.createdBy ?? '—', leftCol, y + 5);
  doc.text(params.customerName, rightCol, y + 5);
  y += 14;

  if (params.source) {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.text('Source', leftCol, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(params.source, leftCol, y + 5);
    y += 12;
  }
  y += 6;

  // ----- Items table -----
  doc.setDrawColor(220, 220, 220);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Items', leftCol, y);
  y += 8;

  doc.setFontSize(9);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);
  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(80, 80, 80);
  doc.text('Item', margin, y);
  doc.text('Qty', 95, y);
  doc.text('Price', 130, y);
  doc.text('Total', 165, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  y += 6;
  doc.line(margin, y, pageW - margin, y);
  y += 5;

  for (const item of params.items) {
    if (y > 265) {
      doc.addPage();
      y = margin;
      doc.setFontSize(9);
    }
    doc.text(item.name.substring(0, 38), margin, y);
    doc.text(String(item.quantity), 95, y);
    doc.text(formatPrice(item.totalPrice), 130, y);
    doc.text(formatPrice(item.totalPrice), 165, y);
    y += 6;
  }

  y += 4;
  doc.line(margin, y, pageW - margin, y);
  y += 10;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Total', margin, y);
  doc.text(formatPrice(params.total), 165, y);
  doc.setFont('helvetica', 'normal');

  // ----- Footer: Generated by Bolo Bill -----
  const footerY = doc.internal.pageSize.getHeight() - 12;
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text(FOOTER_TEXT, pageW / 2, footerY, { align: 'center' });
  doc.setTextColor(0, 0, 0);

  doc.save(`invoice-${params.invoiceId}.pdf`);
}
