import { jsPDF } from 'jspdf';

const BRAND = 'Bolo Bill';
const TITLE = 'Out of Stock – Items Needed';

type OutOfStockItem = { _id: string; name: string; quantity?: string; note?: string };

export function exportOutOfStockPdf(items: OutOfStockItem[]) {
  const doc = new jsPDF();
  const margin = 18;
  const pageW = doc.internal.pageSize.getWidth();
  let y = margin;

  doc.setFillColor(230, 98, 57);
  doc.rect(0, 0, pageW, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(BRAND, margin, 18);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(TITLE, margin, 25);
  doc.setTextColor(0, 0, 0);
  y = 38;

  doc.setFontSize(10);
  doc.text(`Generated on ${new Date().toLocaleString()}`, margin, y);
  y += 10;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Item', margin, y);
  doc.text('Quantity', 90, y);
  doc.text('Note', 130, y);
  doc.setFont('helvetica', 'normal');
  y += 6;
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  for (const item of items) {
    if (y > 270) {
      doc.addPage();
      y = margin;
    }
    doc.setFontSize(9);
    doc.text(item.name.substring(0, 35), margin, y);
    doc.text((item.quantity ?? '—').substring(0, 20), 90, y);
    doc.text((item.note ?? '—').substring(0, 45), 130, y);
    y += 6;
  }

  const footerY = doc.internal.pageSize.getHeight() - 12;
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text(`Generated by ${BRAND}`, pageW / 2, footerY, { align: 'center' });

  doc.save(`out-of-stock-${new Date().toISOString().slice(0, 10)}.pdf`);
}
